notifications:
  irc: irc.freenode.org#vdebug
  slack:
    secure: BksygPSsoRfvre27w6XQN9ooKB9C1n83Bw96YurvyDHJ6BYM2Gv9fW1Sj6NHpB8MQkMaJ+9gRiBSflkP+l80t3EXAdStuI/8EM/wZu1ov6bmYT/hYQ8HnULmmPNj8uVzsX13VGEUC/YY4osWuJFM1wh61dStoF+SKrpslqWCV4w=
language: python
env:
  matrix:
    - DISTRO: 'ubuntu:16.04'
    - DISTRO: 'debian:9'
before_install:
  - docker run --rm -d --name vdebug-distro-test -v $(pwd):/travis $DISTRO tail -f /dev/null
  - docker ps
install:
  - docker exec --env=DEBIAN_FRONTEND=noninteractive vdebug-distro-test apt-get update
    # Vim, php, xdebug, bundler and coverage are needed to run the tests.
    # Xvfb is needed to use the server feature of vim without a running X
    # server (which is needed for some tests).  The locales package is used to
    # set things up inside the container.
  - docker exec --env=DEBIAN_FRONTEND=noninteractive vdebug-distro-test apt-get install -y vim-gtk3 php-cli php-xdebug bundler python3 python3-coverage xvfb locales
  - docker exec vdebug-distro-test bash -c 'echo en_US.UTF-8 UTF-8 >> /etc/locale.gen'
  - docker exec vdebug-distro-test locale-gen
  - docker exec vdebug-distro-test bash -c 'echo LANG=en_US.UTF-8 > /etc/default/locale'
  - docker exec vdebug-distro-test useradd -u $(id -u) -M -s /bin/bash -d /travis travis
  - docker exec vdebug-distro-test su - travis -c 'bundle install --path vendor/bundle'
script:
  - docker exec vdebug-distro-test su - travis -c 'python3-coverage run -m unittest discover'
  - docker exec vdebug-distro-test su - travis -c 'python3-coverage report -m --include="python3/vdebug/*"'
  - docker exec vdebug-distro-test su - travis -c 'xvfb-run bundle exec rake spec features'
